dist: xenial
services:
  - postgresql
  - xvfb
addons:
  postgresql: "9.4"
  chrome: stable
  firefox: latest
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
  - cp decide/local_settings.travis.py decide/local_settings.py
  - "export DISPLAY=:99.0"
  - sleep 3
language: python
python:
- '3.6'
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
  - pip install selenium
  - sudo apt-get install chromium-browser
  - sudo apt-get install -y firefox
  - wget -N https://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip 
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/bin
  - sudo chmod +x /usr/bin/chromedriver
  - wget "https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz"
  - tar xfz geckodriver-v0.27.0-linux64.tar.gz
  - sudo mv -f geckodriver /usr/bin
  - sudo chmod +x /usr/bin/geckodriver
jobs:
  include:
    - script:
      - cd decide
      - ./manage.py collectstatic
      - coverage run --branch --source=. ./manage.py test booth/ --keepdb
      - coverage xml
      - python-codacy-coverage -r coverage.xml
deploy:
  provider: heroku
  app: decide-full-guadalentin-cabina
  strategy: git
  api_key: 
    secure: OcAL9AfBFD7SMiod4/5R34Wf3fsIxIBtVpaejQebAoPaGhLETsUzRKnnvF81HFaJhXVFXg4O9FCAVD2bQKErH/Txud5ACZXxqsDB9NVIbvu2miKogrAqda7rTq8KrueMgmFc/FCvCtHvPgfq+r/3mRUPEf3Hr0mXZ7cHSrAvFK0A0mnykodYZ7o8R+P7lXuL/jB6lI3WByTn6SEtdQvWf4N6xhzGowNssTEWtJrJYFDLVtTZOT93xL8N/5+QBqiSPfdwPGXApZAtfsjwloWFCnSyqMCd0cZAe1sv4YjfxxaH27/v8aEQ4rzPOKY9kzxthWDV41NZfCyVghfYIy+WrY8wCqBhA7FU+x+i8dVJtnqqhCJ+5aHHUT3KUIjY2AYTpl2W/3iDg4zzB7xgX4g6CXTHUWWADDpE7z/BQXYpq2K3ZDkpZxJ5OhjcrdpokrBwc75pl0B2xIxRtqtttKOiDKM48hN93Ub1NwrdtHaGJH4UAVv2D9gCIBU97X2JLYtYS1bPA4bHNqF8jz7J/JtVpnmcixYTUgrGDVwYltZBHlGKAsnh9U4bsIlSzcWJf4YCEi8qgEwBS0N8o0fa43LZdMU2G89C9kDXRAOjf4isN86VgP4O7Oze4VmMGWRmBgM3sjj2+ehN2xjW9K+IoaXoB0pzGcYBoPqiQvb+avDHmvs=
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^cabina.*
notifications:
  email:
    recipients:
      - marmolpen3@alum.us.es
    on_success: never 
    on_failure: always
