dist: xenial
services:
  - postgresql
  - xvfb
addons:
  postgresql: "9.4"
  chrome: stable
  firefox: latest
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
  - cp decide/local_settings.travis.py decide/local_settings.py
  - "export DISPLAY=:99.0"
  - sleep 3
language: python
python:
- '3.6'
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
  - pip install selenium
  - sudo apt-get install chromium-browser
  - sudo apt-get install -y firefox
  - wget -N https://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip 
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/bin
  - sudo chmod +x /usr/bin/chromedriver
  - wget "https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz"
  - tar xfz geckodriver-v0.27.0-linux64.tar.gz
  - sudo mv -f geckodriver /usr/bin
  - sudo chmod +x /usr/bin/geckodriver
script:
  - cd decide
  - coverage run --branch --source=. ./manage.py test booth/tests.py --keepdb --with-xunit
  - coverage xml
  - python-codacy-coverage -r coverage.xml
deploy:
  provider: heroku
  app: decide-full-guadalentin-cabina
  strategy: git
  api_key: 
    secure: cgrIewldGbY/DA9YfFgoaZD+ZbhYuSunUqkxZJpv24dclzXVnfDo37xBBA/U8pDboQGdEuwG9i805UjDewl+PjCnDyFvSWZPLmfGQi0O+P9P+zSRKfgKNyH4ISeJbdh6xnAQOdWgbpR4Ymei9ZYoy887MVB7BzuRTpSq8SUh6/85nCyHJ42NaPP4XxTEQ4xzCTblOJsKbA23LT24yd2/TXwfjYM08Hzidqm5mi6aoESjJ4b9jt88N59ZEvDY1PAAncJf5cPbScB3N94jO9xN35R1TE1tan1NeFV9eZcT9NunLyFnMYhdrYZxF4eelA54rfW2IYwb0pspKZk4GMAO1U/pTuvpIOGbqTFT94aqm4oE85x82FghJGLXlO49W91K2ZgcHOfZm5tUU2itD8y923Y5xR8TmX7gRntlquX17s/3+gjpjOgpLuktajYclFD+xzu+p2TnqUq7NJCw57uVHUG+IzzVpDPDMKF0BB/gjrQHx7xVGNZdE7c7hlunlfOcx4MwKd4/IunlurSsz40wUGcJ/Qqhr4Ak9mRQidGYTRGiVnFtGAr/yID6wrBCiahJC/ibgnRcgBoowLVzqWeYB4WY5aTUPu9gAQf4eC5y7mPX1dQ+/MTjBTOsSXHTPS9VtOIxF0PsogFqg32fRGPW0l3t6IHAK4kTU8fa88tUScg=
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^cabina.*
notifications:
  email:
    recipients:
      - marmolpen3@alum.us.es
    on_success: never 
    on_failure: always
